name: Expo CI/CD with Bun

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install Expo & EAS CLI
        run: bun add -g eas-cli expo-cli json

      - name: Extract Version from Tag
        id: get_version
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Version in app.json
        run: json -I -f app.json -e "this.expo.version='${{ steps.get_version.outputs.VERSION }}'"

      - name: Commit Version Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump version to ${{ steps.get_version.outputs.VERSION }}"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.SPOTLIGHT_GITHUB_TOKEN }}

      - name: Build Android APK
        run: eas build -p android --profile production --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Android APK
        run: eas build:download -p android --profile production --output spotlight-${{ steps.get_version.outputs.VERSION }}.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS IPA
        run: eas build -p ios --profile production --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download iOS IPA
        run: eas build:download -p ios --profile production --output spotlight-${{ steps.get_version.outputs.VERSION }}.ipa
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            spotlight-${{ steps.get_version.outputs.VERSION }}.apk
            spotlight-${{ steps.get_version.outputs.VERSION }}.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.SPOTLIGHT_GITHUB_TOKEN }}

  auto-update:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install EAS CLI
        run: bun add -g eas-cli

      - name: Publish OTA Update
        run: eas update --auto --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
